### PR TITLE
Add regex validation

### PR DESCRIPTION
**Pull request by bitcoinbrisbane**
Check the body to match based on a regex

### CODE REVIEW

**Comment by dlecan** [comment]
Hi, is it possible to review this PR?
I need it too :smile:

**Comment by bitcoinbrisbane** [comment]
Seems the project is dead

**Comment by dlecan** [comment]
@bitcoinbrisbane are you using now another similar tool?

**Comment by dlecan** [comment]
@hassy will you merge this PR if someone updates it?

**Comment by hassy** [comment]
Rebased and merged. Thank you @bitcoinbrisbane and my apologies for how long this took. 😞

**Comment by dlecan** [comment]
:clap: @hassy 
Thank you

**Comment by bitcoinbrisbane** [comment]
No worries, good to see some love again

**Comment by bitcoinbrisbane** [comment]
> @bitcoinbrisbane are you using now another similar tool?

Yeah we dropped artillery.  Might use again if it gets some more love

**Comment by dlecan** [comment]
> @bitcoinbrisbane Yeah we dropped artillery

By curiosity, which tool instead?

**Comment by bitcoinbrisbane** [comment]
Some custom code run from jest off memory

**Pull request merged**
