### PR TITLE
feat: Add less verbose error formatter

### PR DESCRIPTION
**Pull request by FlorianSW**
The formatter is based on the pretty formatter, however it will only print
the contents if one of the expectation results are not ok.

Fixes https://github.com/artilleryio/artillery/issues/630

Co-Authored-by: Arne Wohlert <arne.wohlert@oss.volkswagen.com>

### CODE REVIEW

**Comment by FlorianSW** [comment]
Hi :) Is there anything needed until this PR can be looked on?

**Comment by lcardito** [comment]
Would love to see this moving forward. Seems easy enough and extremely helpful!

**Review by lcardito — APPROVED** [review]

**Comment by GradedJestRisk** [comment]
I'd be glad if this PR would be merged, as `artillery run --quiet my-script.yaml` does not suppress outputs, as mentioned in
https://github.com/artilleryio/artillery-plugin-expect#run-your-test--see-results

**Comment by flentini** [comment]
hey @FlorianSW , thanks for this! could you resolve the merge conflicts so I can merge it ?

**Comment by FlorianSW** [comment]
@flentini Can do that. However, I would like to put the new section for the formatters into the documentation linked from the README. However, when I try to edit this page to create a pull request for it, Github says, that the repository does not exist (https://github.com/artilleryio/documentation/edit/main/source/guides/plugins/plugin-expectations-assertions.md or in short https://github.com/artilleryio/documentation). Is there any error? I could also not find a doc repository by looking at the artilleryio organisation :/

**Comment by flentini** [comment]
@FlorianSW  the documentation repository is currently private, but we are going to make it public soon. I'll merge this PR in the meantime, and sorry if it took a while :sweat_smile:

**Pull request merged**
